language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer install --prefer-source
  - composer self-update

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php coveralls -v